weights: ./runs/train/SCB5-Handrise-Read-write-2024-9-17/exp/weights/last.pt
cfg: ''
data: data/SCB5-Handrise-Read-write-2024-9-17.yaml
hyp: data/hyp.scratch.p5.yaml
epochs: 40
batch_size: 4
img_size:
- 640
- 640
rect: false
resume: true
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
workers: 8
project: runs/train/SCB5-Handrise-Read-write-2024-9-17
entity: null
name: exp
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
world_size: 1
global_rank: -1
save_dir: runs/train/SCB5-Handrise-Read-write-2024-9-17/exp
total_batch_size: 4
